services:
  db:
    # ... existing configuration ...
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d chmit"]
      interval: 5s
      timeout: 5s
      retries: 5
    build: ./db
    restart: always
    environment:    
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: lymm
      POSTGRES_DB: chmit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_BUILD_ENV: true
      POSTGRES_DB_HOST: db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: lymm
      POSTGRES_DB: chmit
    depends_on:
      - db

volumes:
  postgres_data: